# Generated by Django 4.0.4 on 2022-05-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='image', upload_to='projects/'),
        ),
    ]
