# Generated by Django 4.0.4 on 2022-05-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_name_about_first_name_about_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
