# Generated by Django 4.0.4 on 2022-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_about_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(default='image', upload_to='abouts/'),
        ),
    ]
