# Generated by Django 4.0.4 on 2022-05-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_about_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
