# Generated by Django 4.0.4 on 2022-05-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('profile_image', models.ImageField(default='image', upload_to='abouts/')),
            ],
        ),
    ]
