# Generated by Django 4.0.4 on 2022-05-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
    ]
