# Generated by Django 4.0.4 on 2022-05-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_about_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_url',
            field=models.URLField(default='', max_length=50),
        ),
    ]
